# Generated by Django 4.1.3 on 2023-01-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messagepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepost',
            name='message',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagepost',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
